### PR TITLE
added likert styling to dospoert eb

### PR DESCRIPTION
**Pull request by IanEisenberg**
Added styling. This moves the labels underneath each radio button and keeps that fixed distance apart. Because distance is important, I fixed the width of the survey. This works as long as the window is larger than the survey's width (otherwise is gets squished, as you can see below).

Looking good
full

Not so good
squish

### CODE REVIEW

**Comment by vsoch** [comment]
Could you please center the content on the newly widened page?

**Comment by vsoch** [comment]
I'm not sure what the association for "looking good" and "not so good" is.

**Comment by IanEisenberg** [comment]
"Not so good" just related to the fact that the narrower image doesn't narrow very nicely. I don't know what a better alternative is, but it looks a bit weird. no problem if they don't narrow their web page.

I can certainly center the content, but content has never been centered so I just stayed consistent. See below:

previous

**Comment by vsoch** [comment]
For the above image it's not an issue because the question text is in line with the radio text, and it looks clean. For the version you shared, this visual unity is broken, and so the style needs to be further adjusted so it doesn't look as "off" as it does now. Make sense?

**Comment by IanEisenberg** [comment]
Yep.

**Comment by vsoch** [comment]
It should just be a matter of making the text div have equal left margin to the question text div. Looking forward to seeing it! :)

**Comment by IanEisenberg** [comment]
new view. A little difficult for me to figure out how to move the labels over without moving the text on non-radio pages (like the initial instruction pages). Ended up using the margin-left property

new

**Comment by IanEisenberg** [comment]
Styling can be applied to other likert like surveys by changing the width of the overall survey. Centering in other ways is proving difficult due to the lack of likert specific div. This works fine though

bis

**Comment by IanEisenberg** [comment]
Using a list or divs for each likerty scale we could add that [little line](http://codepen.io/Buttonpresser/pen/qiuIx) (which may or may not be helpful - may just clutter the page.

**Comment by IanEisenberg** [comment]
It could look like this. Right now the button background isn't "white", it's transparent. But if I fix that this looks good.

lines

**Comment by vsoch** [comment]
@IanEisenberg  the last picture, and second to last picture, beautiful! Which one is reflected in this PR? I think for Likert, the last one is the best - it communicates that the scale is connected. Since the width may be custom depending on the Likert, let's go with the last one, and add the appropriate style.css for each survey you add to. I see you edited two versions of the dospert - send me a quick screen shot of the final one for each reflected in the PR, and then I'll go ahead and merge. Beautiful work!

**Comment by IanEisenberg** [comment]
@vsoch, the second to last picture (no lines) is currently in this PR). The lines go through the radio buttons (they are transparent) and I'm not sure if I can make the radio button's backgrounds white instead of transparent. I have an idea, and if it works out I'll add to this PR, otherwise I'll update the rest of the surveys and we can merge.

**Comment by vsoch** [comment]
Can you add to the PR so I can take a look? I think if we are going "likert," we should "go all the way." :)

**Comment by IanEisenberg** [comment]
Sure. I'll add in a few minutes

**Comment by IanEisenberg** [comment]
Updated. I'm having trouble getting the line on the first three elements. The nth-child indexing is not working as I'd expect for this form.
screenshot from 2016-04-15 11 14 08

**Comment by vsoch** [comment]
Didn't you have it before? What happened?

**Comment by IanEisenberg** [comment]
Before it looked like below, where the line just runs through all the radio buttons. The current PR adds a small line after each button to the next. This is how it looked before:

linethrough

**Comment by vsoch** [comment]
ah I see - I'm working on games right now but will take a look in a bit.

**Comment by vsoch** [comment]
Can you show the styling (copy paste here is fine) you were using for the last picture?

**Comment by IanEisenberg** [comment]
Last picture (one line going across):
form p:before {
  content: '';
  position:relative;
  top:53px;
  left:61px;
  display:block;
  background-color:#efefef;
  height:4px;
  width:435px;
}

Previous picture (2 small lines)
form .current .mdl-radio:nth-child(3n):before {
    content: '';
    position: relative;
    top: 10px;
    left: -10px;
    display: block;
    background-color: #efefef;
    height: 4px;
    width: 135px;
}

form .current .mdl-radio:nth-child(3n+1):before {
    content: '';
    position: relative;
    top: 10px;
    left: -10px;
    display: block;
    background-color: #efefef;
    height: 4px;
    width: 135px;
}

**Comment by vsoch** [comment]
ok, I got it working, will send PR to your branch soon.

**Comment by vsoch** [comment]
See https://github.com/IanEisenberg/expfactory-surveys/pull/1

**Comment by IanEisenberg** [comment]
Our solution works for surveys with one kind of question, but fails for surveys like [this](http://expfactory.org/experiments/five_facet_mindfulness_survey/preview).

I'm going to deal with such surveys by being very pedantic about the styling (for each individual <p> basically)

**Comment by vsoch** [comment]
That is my intuition for now as well - add a custom style.css to get it perfect for each likert, and we can address a "one size fits all" solution in the future.

**Comment by IanEisenberg** [comment]
Updated all surveys and tested. Ready to merge.

**Comment by vsoch** [comment]
ok, let me give a quick look.

**Comment by vsoch** [comment]
So beautiful! Just a few tweaks:

### brief_self_control_survey

the survey needs to be widened and centered, like bis_bas, etc.

### dospert_\* surveys

the alignment is first on the left:

image

and then it jumps to the right:

image

This is also true for erq_survey, please center for all.

### five_facet_mindfullness

Add a bit more left padding, eg here is 25px:

image

### grit_scale_survey

Please widen and center, like (same issue as brief_self_control_survey)

### mindful_attention_awareness_survey

spacing inside white page looks great! Please move the entire box slightly more to the left so it is centered:

image

### self_regulation_survey

also just needs to move a smidge to the left (maybe 5px?) so it is centered:

image

### ten_item_personality

also needs more like 25px for the left margin:

image

### theories_of_willpower

same issue as above for left margin, and the margins within the white page are slightly off center (left is a little too big)

image

### time_perspective_survey

white page area needs to move to the left maybe 5-10px to make centered:

image

That's it! We're almost there! This is a huge improvement for the Likert!

**Comment by vsoch** [comment]
reviewing now.

**Comment by vsoch** [comment]
brief_self_control looks good!

### erq_survey

I didn't see any changes - this is my fault for mentioning it under the dospert_\* section and not giving it a bold name. It has the same issue with changing width as the dospert_\* surveys did.

### dospert_rp_survey

still jumps to the left, here is the first page:

image

and the survey:

image

### dospert_rt_survey

image

and then:

image

dospert_eb looks great.

### five_facet_mindfullness

first here

image

 then jumps left and down

image

grit_scale, mindful_attention_awareness, self_regulation_survey, theories_of_willpower, time_perspective_survey, perfecto!

**Comment by IanEisenberg** [comment]
Thanks for the review. I'll get to those soon

On Saturday, April 16, 2016, Vanessa Sochat notifications@github.com
wrote:

> brief_self_control looks good!
> erq_survey
> 
> I didn't see any changes - this is my fault for mentioning it under the
> dospert_\* section and not giving it a bold name. It has the same issue with
> changing width as the dospert_\* surveys did.
> dospert_rp_survey
> 
> still jumps to the left, here is the first page:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/814322/14582461/7eb9372c-03ba-11e6-8a10-1076b9a25b42.png
> 
> and the survey:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/814322/14582468/947160ee-03ba-11e6-8be8-7085bb815e39.png
> dospert_rt_survey
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/814322/14582480/de60bd12-03ba-11e6-8451-6f43bd7d06d7.png
> 
> and then:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/814322/14582482/faf0271a-03ba-11e6-9a27-e1ea6baf8090.png
> 
> dospert_eb looks great.
> five_facet_mindfullness
> 
> first here
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/814322/14582494/52aba5ce-03bb-11e6-9fbe-8ffe54d31c93.png
> 
> then jumps left and down
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/814322/14582497/630d5a8e-03bb-11e6-8853-04a5bbd16330.png
> 
> grit_scale, mindful_attention_awareness, self_regulation_survey,
> theories_of_willpower, time_perspective_survey, perfecto!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/expfactory/expfactory-surveys/pull/47#issuecomment-210860960

## 

Best,
Ian

**Comment by vsoch** [comment]
great!

**Comment by IanEisenberg** [comment]
These issues relate to my limited understanding of mdl. There is this mdl-cell object which seems to be responsible for centering content. It's what I've been changing to center the content. It is set to a particular width (see below) and will shrink done to nothing when the page becomes too narrow. I don't know why it is changing its behavior based on the page you are on (all pages should be identical, right?). When full screen I don't get these issues - do you for a full screen window?

This is the syntax I am using:
.mdl-cell--2-col, .mdl-cell--2-col-desktop.mdl-cell--2-col-desktop {
  width: calc(9.5% - 16px)
}

**Comment by vsoch** [comment]
You don't want to change the style of the mdl cell type, you likely want to change the class entirely. [Here are the docs](http://www.getmdl.io/components/index.html#layout-section).

**Comment by IanEisenberg** [comment]
Hey @vsoch, I'm having trouble figuring out what to do here and could use some help! I'm not recreating the "switching" from page to page - I'm only getting the jumping when I reduce the size of the window, but it affects all pages equally. I'm also not sure how to edit the mdl-cell class itself, as any change seems to be overwritten by higher-level (lower-level?) styling classes.

**Comment by vsoch** [comment]
To force editing the class, just add the !important tag to the css, eg:

```
  .stylename {
         color: red !important;
   }
```

**Comment by IanEisenberg** [comment]
Thanks. I'll try that.

On Fri, Apr 22, 2016 at 2:20 PM, Vanessa Sochat notifications@github.com
wrote:

> To force editing the class, just add the !important tag to the css, eg:
> 
>   .stylename {
>          color: red !important;
>    }
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/expfactory/expfactory-surveys/pull/47#issuecomment-213592365

## 

Best,
Ian

**Comment by IanEisenberg** [comment]
Finally had time to come back to these. I am not recreating the jumping error between pages. When the page becomes too small it jumps a bit to the side, but that happens even with default mdl styling.

Also, you mentioned that dospert_eb looks good but dospert_rp  doesn't (it has the jumping problem), but their style.css is the same.

@rwblair, I'll come by this week and see if you can recreate these errors (if you have time). I could use some help with these little final things! Really want to get these surveys up.

**Comment by IanEisenberg** [comment]
I think my meeting with @rwblair lead to a solution! We have removed the mdl-cell that disappears at particular screen widths and used a much simpler centering procedure. Centering is better now and there should be no jump.

**Comment by vsoch** [comment]
Excellent job @IanEisenberg and @rwblair, these are flawless.

**Pull request merged**
